const copyVariant = "B" as const;

const AppCopywritingVariants = {
  A: {
    home: {
      subtitle: "紫罗兰来信",
      tagline: "在柔和留白与静谧色调里，挑选今日想寄出的风景。",
      mobileDesc: "按主题翻阅，为手机挑一张安静封面",
      avatarDesc: "收集精致头像，为你的名片添一枚印章",
    },
    mobile: {
      heroText: "像翻阅信件目录一样，找到适合主屏的画面。",
      pickCategory: "选择分类",
      all: "全部",
      featured: "精选",
      backToCategory: "返回分类",
      emptyFeaturedInCategory: "这封分类信笺里还没有精选壁纸",
      emptyFeaturedAll: "暂时还没有精选手机壁纸",
      emptyInCategory: "这封分类信笺里还没有壁纸",
      emptyAll: "暂时还没有手机壁纸",
      loadingMore: "正在整理下一页信笺…",
      loadMore: "上拉翻阅更多",
      noMore: "已翻到最后一页",
      sheet: {
        title: "信笺操作",
        home: "设为主屏壁纸",
        lock: "设为锁屏壁纸",
        both: "主屏与锁屏同时设置",
        cancel: "先放回信封",
      },
      alert: {
        tip: "提示",
        fail: "失败",
        success: "成功",
        setFail: "设置失败",
        androidOnly: "设置壁纸仅支持 Android 设备，请在 Android 手机上尝试。",
        noImage: "未能读取图片地址，请稍后重试。",
        unsupported:
          "当前环境暂不支持设置壁纸，请使用开发版或正式包（Expo Go 不支持）。",
        setSuccess: "壁纸已设置完成。",
        setFailedFallback: "设置壁纸失败，请重试。",
        retryTip: "请使用开发版或正式包重试（Expo Go 不支持）。",
      },
    },
    avatar: {
      title: "头像壁纸",
      all: "全部",
      featured: "精选",
      emptyFeatured: "暂时还没有精选头像壁纸",
      emptyAll: "暂时还没有头像壁纸",
      loadingMore: "正在整理下一页信笺…",
      loadMore: "上拉翻阅更多",
      noMore: "已翻到最后一页",
      sheet: {
        title: "保存到相册",
        download: "收下这张头像",
        cancel: "先放回信封",
      },
      alert: {
        tip: "提示",
        fail: "失败",
        success: "成功",
        needPermission: "需要权限",
        downloadFail: "下载失败",
        webTip: "请在手机 App 中保存到相册。",
        noImage: "未能读取图片地址，请稍后重试。",
        permissionContent: "请允许保存到相册，否则无法在相册中查看。",
        saveSuccess: "已保存到相册，你可以在相册/图库中查看。",
        retryTip: "请稍后重试。",
      },
    },
  },
  B: {
    home: {
      subtitle: "紫罗兰手札",
      tagline: "把今日心绪折进信笺，在一张壁纸里轻轻落款。",
      mobileDesc: "循着主题翻页，为主屏挑一封恰到好处的来信",
      avatarDesc: "挑选一枚头像，让初见也有温柔回信",
    },
    mobile: {
      heroText: "像查阅邮册一样，按线索找到与你同频的画面。",
      pickCategory: "挑选信笺分类",
      all: "全部",
      featured: "珍选",
      backToCategory: "回到分类目录",
      emptyFeaturedInCategory: "这封分类来信里，暂时还没有珍选壁纸",
      emptyFeaturedAll: "邮袋里暂时还没有珍选手机壁纸",
      emptyInCategory: "这封分类来信里，暂时还没有壁纸",
      emptyAll: "邮袋里暂时还没有手机壁纸",
      loadingMore: "正在整理下一叠来信…",
      loadMore: "上拉继续翻阅",
      noMore: "这一册已翻阅完毕",
      sheet: {
        title: "信封操作",
        home: "落款到主屏",
        lock: "落款到锁屏",
        both: "同时落款到主屏与锁屏",
        cancel: "先合上信封",
      },
      alert: {
        tip: "提示",
        fail: "失败",
        success: "成功",
        setFail: "设置失败",
        androidOnly:
          "目前仅支持在 Android 设备上设置壁纸，请换用 Android 手机尝试。",
        noImage: "这封来信暂时读不到图片地址，请稍后再试。",
        unsupported:
          "当前环境暂不支持设置壁纸，请使用开发版或正式包（Expo Go 不支持）。",
        setSuccess: "壁纸已落款完成。",
        setFailedFallback: "落款失败，请再试一次。",
        retryTip: "请使用开发版或正式包重试（Expo Go 不支持）。",
      },
    },
    avatar: {
      title: "头像壁纸",
      all: "全部",
      featured: "珍选",
      emptyFeatured: "暂时还没有珍选头像壁纸",
      emptyAll: "暂时还没有头像壁纸",
      loadingMore: "正在整理下一叠来信…",
      loadMore: "上拉继续翻阅",
      noMore: "这一册已翻阅完毕",
      sheet: {
        title: "收纳到相册",
        download: "收下这封头像来信",
        cancel: "先合上信封",
      },
      alert: {
        tip: "提示",
        fail: "失败",
        success: "成功",
        needPermission: "需要权限",
        downloadFail: "下载失败",
        webTip: "请在手机 App 中保存到相册。",
        noImage: "这封来信暂时读不到图片地址，请稍后再试。",
        permissionContent: "请允许保存到相册，否则无法在相册中查看。",
        saveSuccess: "已收纳到相册，你可以在相册/图库中查看。",
        retryTip: "请稍后重试。",
      },
    },
  },
} as const;

export const AppCopywriting = AppCopywritingVariants[copyVariant];
