/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dictionaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询整个字典表
         * @description 查询整个字典表，返回所有数据（不分页）。
         */
        get: operations["get_all_dictionaries_api_dictionaries__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pictures/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传壁纸
         * @description 上传新壁纸，提取图片属性，并返回预签名下载链接和元数据。
         *
         *     返回的元数据包括：
         *     - width, height: 图片尺寸（像素）
         *     - format: 图片格式（JPEG, PNG 等）
         *     - mode: 颜色模式（RGB, RGBA 等）
         *     - size_bytes: 文件大小
         *     - md5: 文件 MD5 哈希（用于去重）
         *     - dpi: 分辨率（如果有）
         */
        post: operations["upload_wallpaper_api_pictures__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pictures/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询壁纸列表
         * @description 分页查询壁纸列表，按创建时间倒序排列。
         */
        get: operations["list_wallpapers_api_pictures_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pictures/{picture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询单个图片详情
         * @description 根据图片ID查询单个图片的所有信息。
         */
        get: operations["get_picture_api_pictures__picture_id__get"];
        /**
         * 编辑壁纸信息
         * @description 编辑壁纸信息，主要修改标签、分类、审核状态。
         */
        put: operations["update_wallpaper_api_pictures__picture_id__put"];
        post?: never;
        /**
         * 删除壁纸
         * @description 删除指定壁纸。先删除 MinIO 文件，再删除数据库记录。
         */
        delete: operations["delete_wallpaper_api_pictures__picture_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pictures/{picture_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下载图片
         * @description 根据图片ID下载图片，返回图片流。
         */
        get: operations["download_picture_api_pictures__picture_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pictures/{picture_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 增加图片预览次数
         * @description 增加图片的预览次数。
         */
        post: operations["increment_picture_view_api_pictures__picture_id__view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建标签
         * @description 创建新标签。
         */
        post: operations["create_tag_api_tags__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询所有标签列表
         * @description 查询所有标签列表，按点击次数倒序排列。
         */
        get: operations["list_tags_api_tags_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除标签
         * @description 删除指定标签。
         */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 根路径
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_wallpaper_api_pictures__post */
        Body_upload_wallpaper_api_pictures__post: {
            /**
             * File
             * Format: binary
             * @description 壁纸文件
             */
            file: string;
            /**
             * Tags
             * @description 标签
             * @default []
             */
            tags: string[];
            /**
             * Category
             * @description 分类
             */
            category: string;
        };
        /** RequestValidationError */
        HTTPValidationError: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            errors: components["schemas"]["ValidationError"][];
        };
        /**
         * PictureQueryResponse
         * @description 图片响应模型
         */
        PictureQueryResponse: {
            /**
             * Page Num
             * @description 页码，从 1 开始
             * @default 1
             */
            page_num: number;
            /**
             * Page Size
             * @description 每页数量，最大 100
             * @default 20
             */
            page_size: number;
            /**
             * Records
             * @description 图片列表
             */
            records: components["schemas"]["PictureResponseInfo"][];
            /**
             * Total
             * @description 总记录数
             */
            total: number;
        };
        /**
         * PictureResponseInfo
         * @description 图片分页查询响应模型
         */
        PictureResponseInfo: {
            /**
             * Id
             * @description 主键
             */
            id: number;
            /**
             * Original Filename
             * @description 原始文件名
             */
            original_filename?: string | null;
            /**
             * Width
             * @description 图片宽度（px）
             */
            width: number;
            /**
             * Height
             * @description 图片高度（px）
             */
            height: number;
            /**
             * Webp Url
             * @description 压缩WebP预签名预览链接
             */
            webp_url?: string | null;
            /**
             * Thumbnail Url
             * @description 缩略图WebP预签名预览链接
             */
            thumbnail_url?: string | null;
            /**
             * Device Type
             * @description 设备类型：1=PC端，2=移动端，3=头像
             */
            device_type?: number | null;
            /**
             * Category
             * @description 分类
             */
            category?: string | null;
            /**
             * View Count
             * @description 预览次数
             * @default 0
             */
            view_count: number;
            /**
             * Download Count
             * @description 下载次数
             * @default 0
             */
            download_count: number;
            /**
             * Tags
             * @description 标签列表
             */
            tags?: string[] | null;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
            /**
             * Status
             * @description 审核状态：0=未审核，1=通过，2=未通过
             */
            status: number;
        };
        /**
         * PictureUpdateRequest
         * @description 图片更新请求模型
         */
        PictureUpdateRequest: {
            /**
             * Status
             * @description 审核状态：0=未审核，1=通过，2=未通过
             */
            status?: number | null;
            /**
             * Category
             * @description 分类
             */
            category?: string | null;
            /**
             * Tags
             * @description 标签列表
             */
            tags?: string[] | null;
        };
        /**
         * PictureUploadResponse
         * @description 图片上传响应模型
         */
        PictureUploadResponse: {
            /**
             * Id
             * @description 主键
             */
            id: number;
            /**
             * Bucket
             * @description 对象存储桶名称
             */
            bucket: string;
            /**
             * Object Name
             * @description 原图对象名（MinIO key）
             */
            object_name: string;
            /**
             * Original Filename
             * @description 原始文件名
             */
            original_filename?: string | null;
            /**
             * Width
             * @description 图片宽度（px）
             */
            width: number;
            /**
             * Height
             * @description 图片高度（px）
             */
            height: number;
            /**
             * Format
             * @description 图片格式（JPEG/PNG等）
             */
            format: string;
            /**
             * Mode
             * @description 颜色模式（RGB/RGBA等）
             */
            mode: string;
            /**
             * Size Bytes
             * @description 文件大小（字节）
             */
            size_bytes: number;
            /**
             * Md5
             * @description 文件 MD5，用于去重
             */
            md5: string;
            /**
             * Dpi
             * @description DPI 信息（JSON）
             */
            dpi?: {
                [key: string]: unknown;
            } | null;
            /**
             * Url
             * @description 原图预签名预览链接
             */
            url?: string | null;
            /**
             * Webp Object Name
             * @description 压缩WebP对象名
             */
            webp_object_name?: string | null;
            /**
             * Webp Url
             * @description 压缩WebP预签名预览链接
             */
            webp_url?: string | null;
            /**
             * Thumbnail Object Name
             * @description 缩略图WebP对象名
             */
            thumbnail_object_name?: string | null;
            /**
             * Thumbnail Url
             * @description 缩略图WebP预签名预览链接
             */
            thumbnail_url?: string | null;
            /**
             * Device Type
             * @description 设备类型：1=PC端，2=移动端，3=头像
             */
            device_type?: number | null;
            /**
             * Status
             * @description 审核状态：0=未审核，1=通过，2=未通过
             * @default 0
             */
            status: number;
            /**
             * Category
             * @description 分类
             */
            category?: string | null;
            /**
             * View Count
             * @description 预览次数
             * @default 0
             */
            view_count: number;
            /**
             * Download Count
             * @description 下载次数
             * @default 0
             */
            download_count: number;
            /**
             * Tags
             * @description 标签列表
             */
            tags?: string[] | null;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
        };
        /**
         * TagCreateRequest
         * @description 标签创建请求模型
         */
        TagCreateRequest: {
            /**
             * Name
             * @description 标签名称
             */
            name: string;
        };
        /**
         * TagResponse
         * @description 标签响应模型
         */
        TagResponse: {
            /**
             * Id
             * @description 主键
             */
            id: number;
            /**
             * Name
             * @description 标签名称
             */
            name: string;
            /**
             * Click Count
             * @description 点击次数
             */
            click_count: number;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Problem */
        Problem: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            /** Problem detail */
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_dictionaries_api_dictionaries__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    upload_wallpaper_api_pictures__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_wallpaper_api_pictures__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_wallpapers_api_pictures_list_get: {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始 */
                page_num?: number;
                /** @description 每页数量，最大 100 */
                page_size?: number;
                /** @description 图片格式筛选（如 JPEG、PNG） */
                format?: string | null;
                /** @description 最小宽度（px） */
                min_width?: number | null;
                /** @description 最大宽度（px） */
                max_width?: number | null;
                /** @description 最小高度（px） */
                min_height?: number | null;
                /** @description 最大高度（px） */
                max_height?: number | null;
                /** @description 原始文件名（模糊匹配） */
                original_filename?: string | null;
                /** @description 设备类型：1=PC端，2=移动端，3=头像 */
                device_type?: number | null;
                /** @description 审核状态：0=未审核，1=通过，2=未通过 */
                status?: number | null;
                /** @description 分类 */
                category?: string | null;
                /** @description 标签列表 */
                tags?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_picture_api_pictures__picture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                picture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_wallpaper_api_pictures__picture_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                picture_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PictureUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureResponseInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_wallpaper_api_pictures__picture_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                picture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    download_picture_api_pictures__picture_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                picture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    increment_picture_view_api_pictures__picture_id__view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                picture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_tag_api_tags__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_tags_api_tags_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
